;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        keyboard-escape-quit
        ))
